config/routes.rb
WiscLandWebApp::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "mobile/sessions" }
  
  devise_scope :user do
    namespace :mobile do
        resources :sessions, :only => [:create, :destroy]
    end
  end

  resources :users do
    member do
      post 'assignments'
    end
  end

  resources :users do
    collection do
      post 'approve'
    end
  end
  
  get '/classifications/index' => 'classification#index'
  get '/forest_types/index' => 'forest_types#index'
  get '/vegetations/index' => 'vegetations#index'

  get '/dashboard/roles' => 'dashboard#roles', :as => 'roles'
  get '/dashboard/classifications' => 'dashboard#classifications', :as => 'classifications'
  get '/dashboard/tasks' => 'dashboard#tasks', :as => 'tasks'

  post '/assignments/assignTasks' => 'assignments#assignTasks'
  post '/assignments' => 'assignments#index'
  post '/dashboard/roleCheck' => 'dashboard#roleCheck'
  post '/dashboard/roleAdd' => 'dashboard#addRole'
  post '/field_datas/submit' => 'field_datas#submit'
  post '/field_datas/getFieldDataDetails' => 'field_datas#getFieldDataDetails'

  resources :field_datas
  resources :assignments do
    collection do
      post 'getTasks'
    end
  end

  resources :dashboard do
    collection do
      post 'roleCheck'
      post 'roleAdd'
    end
  end
  
  root to: "login#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :user
	belongs_to :location
	has_many :field_datas
end

app/models/classification.rb
class Classification < ActiveRecord::Base
end

app/models/field_data.rb
class FieldData < ActiveRecord::Base
	belongs_to :assignment
	has_many :species_entries
end

app/models/forest_type.rb
class ForestType < ActiveRecord::Base
	has_many :species_entries
end

app/models/location.rb
class Location < ActiveRecord::Base
	has_one :assignment
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/species_entry.rb
class SpeciesEntry < ActiveRecord::Base
	belongs_to :forest_type
	belongs_to :field_data
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :assignments

  def active_for_authentication? 
    super && approved? 
  end 

def inactive_message 
  if !approved? 
    :not_approved 
  else 
    super # Use whatever other message 
  end 
end

  # protected
  # 	def confirmation_required?
  # 		false
  # 	end

end

app/models/vegetation.rb
class Vegetation < ActiveRecord::Base
end

app/models/vegetation_entry.rb
class VegetationEntry < ActiveRecord::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # def devise_error_messages!
  #   # return '' if resource.errors.empty?

  #   # messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
  #   # html = <<-HTML
  #   # <div class="alert alert-error alert-block"> <button type="button"
  #   # class="close" data-dismiss="alert">x</button>
  #   #   #{messages}
  #   # </div>
  #   # HTML

  #   # html.html_safe
  # end
end

app/helpers/field_datas_helper.rb
module FieldDatasHelper
end

app/helpers/forest_types_helper.rb
module ForestTypesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vegetations_helper.rb
module VegetationsHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
                  <div class="container">
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar">
                        </span>
    <span class="icon-bar">
                        </span>
    <span class="icon-bar">
                        </span>
    </button>
    <ul class="nav navbar-nav">
        <li>
          <%= link_to "Wisconsin Land Cover Mapping Field Validation Tool", dashboard_index_path, :method => :get %>
        </li>
    </ul>
    </div>
    <!--/.navbar-collapse -->
    <div class="navbar-collapse collapse pull-right">
      <ul class="nav navbar-nav">
        <li class="active">
        </li>
        <li>
          <% if current_user.has_role :admin %>
            <li> <%= link_to "Role Management", roles_path, :method => :get %></li>
          <% end %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <%= current_user.email %> &nbsp;
                            <b class="caret">
                            </b>
                          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="#">
                                Profile
                              </a>
            </li>
            <li>
              <a href="#">
                                Settings
                              </a>
            </li>
            <li> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            <li class="divider">
            </li>
          </ul>
        </li>
      </ul>
    </div>
    </div>
    </div>

app/views/layouts/_logo.html.erb
<div id="logoDiv">
  <img id="logo" src="http://upload.wikimedia.org/wikipedia/en/e/ed/UW-Madison_logo.svg">
  <h1> Wisconsin Land Map Tool </h1>
</div>

app/views/layouts/_map.html.erb
        <div id="mapDiv"></div>
      </div>
    </div>
    <div id="info">
      <div><center>Tools</center></div>
        <button id="Polygon" class='btn btn-default btn-block' >Draw</button>
        <button id="assign" class='btn btn-default btn-block'>Assign</button>
        <button id="clear"  class='btn btn-default btn-block'>Clear</button>
    </div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>WiscLandWebApp</title>
  <link rel="stylesheet" href="http://js.arcgis.com/3.8/js/esri/css/esri.css">
  <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="http://js.arcgis.com/3.8/"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>



</head>
<body>

<% if user_signed_in? %>
	<%= render 'layouts/header' %>
	<div id="page-content-wrapper">
        <!-- Keep all page content within the page-content inset div! -->
        <div class="page-content inset">


<% else %>
	<%= render 'layouts/logo' %>
<% end %>

<%= render 'layouts/messages' %>

<%= yield %>

		</div>
    </div>
</body>
</html>